config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  resources :transactions
  resources :accounts
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :user
	has_many :transactions, dependent: :destroy
	accepts_nested_attributes_for :transactions, allow_destroy: true

    validates :ac_type, :opening_date,:status,:user_id, presence: true

	before_create :change_ac_id
	def change_ac_id
		acc_id = Random.new.bytes(5).bytes.join[0,5]
		self.ac_no=acc_id
		self.balance=self.transactions[0].tx_amount
	end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
    @transaction = @account.transactions.build
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:user_id, :ac_no, :ac_type, :opening_date, :closing_date, :balance, :status, transactions_attributes: [:account_id, :tx_date, :tx_amount, :tx_type, :id])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= form.label :ac_no %>
    <%#= form.text_field :ac_no %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%#= hidden_field_tag :user_id, current_user.id%>
  </div>

  <div class="field">
    <%= form.label :ac_type %>
    <%#= form.text_field :ac_type %>
    <%= form.select :ac_type, ['Saving', 'Open'], :prompt => 'Select One' %>
  </div>

  <div class="field">
    <%= form.label :opening_date %>
    <%= form.datetime_select :opening_date %>
  </div>

  <div class="field">
    <%= form.label :closing_date %>
    <%= form.datetime_select :closing_date %>
  </div>


  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ['Active', 'Inactive'], :prompt => 'Select One' %>
  </div>

  <%= form.fields_for :transactions do |f|%>
      <div class="field">
        <%= f.label :tx_amount %>
        <%= f.text_field :tx_amount %>
      </div>
      <div class="field">
        <%= f.label :tx_date %>
        <%= f.datetime_select :tx_date %>
      </div>

      <div class="field">
        <%= f.label :tx_type %>
        <%= f.select :tx_type, ['Credit'], :prompt => 'Select One' %>
      </div>


  <%end%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Ac no</th>
      <th>Ac type</th>
      <th>Opening date</th>
      <th>Closing</th>
      <th>Balance</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.ac_no %></td>
        <td><%= account.ac_type %></td>
        <td><%= account.opening_date %></td>
        <td><%= account.closing_date %></td>
        <td><%= account.balance %></td>
        <td><%= account.status %></td>
        <td><%= link_to 'Show', account %></td>
        <!-- <td><%= link_to 'Edit', edit_account_path(account) %></td> -->
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ac no:</strong>
  <%= @account.ac_no %>
</p>

<p>
  <strong>Ac type:</strong>
  <%= @account.ac_type %>
</p>

<p>
  <strong>Opening date:</strong>
  <%= @account.opening_date %>
</p>

<p>
  <strong>Closing:</strong>
  <%= @account.closing_date %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<p>
  <strong>Status:</strong>
  <%= @account.status %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>